import React, { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Container, Row, Col, Button, Form, Card, Alert } from 'react-bootstrap';
import 'bootstrap/dist/css/bootstrap.min.css';
import { FaCloudUploadAlt, FaCheckCircle, FaFileAlt } from 'react-icons/fa';
import './LandingPage.css';
import { useTheme } from "../ThemeContext";

function LandingPage() {
  const navigate = useNavigate();
  const { isDarkMode } = useTheme()
  const themeClass = isDarkMode ? 'dark bg-dark text-light' : 'light' 


  return (
    <div className="landing-page">
      <header className={`hero-section d-flex justify-content-center align-items-center text-center ${themeClass}`} style={{ height: '100vh' }}>
        <Container>
          <Row>
            <Col md={12}>
              <h1 className={`display-4 ${themeClass}`}>Audit Your IT Environment with Pipsqueak</h1>
              <p className={`lead ${themeClass}`}>Upload your scan result to get a detailed audit of your code and security.</p>
              <div className={`mt-4 ${themeClass}`}>
                <Button variant='primary' size="lg" onClick={() => navigate('/register')} className={`mx-2`}>
                  Sign Up
                </Button>
                <Button variant='outline-primary' size="lg" onClick={() => navigate('/login')} className={`mx-2`}>
                  Login
                </Button>
              </div>
            </Col>
          </Row>
        </Container>
      </header>

   

      {/* How It Works Section */}
      <section className={`${themeClass}`}>
        <Container>
          <Row>
            <Col md={4}>
              <Card className={`text-center ${themeClass}`}>
                <Card.Body>
                  <FaCloudUploadAlt size={50} />
                  <h4 className={`mt-3 ${themeClass}`}>Upload Your Scan Result</h4>
                  <p>Upload the JSON file generated by Pipsqueak for audit.</p>
                </Card.Body>
              </Card>
            </Col>
            <Col md={4}>
              <Card  className={`text-center ${themeClass}`}>
                <Card.Body>
                  <FaFileAlt size={50} />
                  <h4 className="mt-3">Process the Data</h4>
                  <p>Pipsqueak processes your scan result file and runs an audit.</p>
                </Card.Body>
              </Card>
            </Col>
            <Col md={4}>
              <Card  className={`text-center ${themeClass}`}>
                <Card.Body>
                  <FaCheckCircle size={50} />
                  <h4 className="mt-3">View Your Audit Results</h4>
                  <p>Receive insights, security tips, and recommendations from the audit results.</p>
                </Card.Body>
              </Card>
            </Col>
          </Row>
        </Container>
      </section>

      {/* Footer Section */}
      <footer className="text-center py-4 bg-dark text-white">
        <Container>
          <Row>
            <Col>
              <p>Questions? <Link to="/contact" className="text-light">Contact us</Link> or check our{' '}
                <Link to="/faq" className="text-light">FAQ</Link>.</p>
            </Col>
          </Row>
        </Container>
      </footer>
    </div>
  );
}

export default LandingPage;
